name: "Build and Deploy"
env:
  SEMVER: ${{ format('0.1.2-alpha+{0}', github.run_id ) }}
  
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:        
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    name: Build Package
    runs-on: ubuntu-latest
          
    steps:
    #- name: Dump GitHub context
    #  env: 
    #    GITHUB_CONTEXT: ${{ toJson(github) }}
    #  run: echo "$GITHUB_CONTEXT"
    
      
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:Version=${{ env.SEMVER }}
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Pack
      run: dotnet pack Math.Net.StreamingStats --configuration Release -o finalpackage --no-build -p:PackageVersion=${{ env.SEMVER }}
    
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: nupkg
        path: finalpackage
        
  deploy:
    needs: build
    name: Deploy Packages
    runs-on: windows-latest # using windows agent due to nuget can't sign on linux yet
    steps:
      - name: Download Package artifact
        uses: actions/download-artifact@master
        with:
          name: nupkg
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: latest

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      - name: Push to NuGet
        run: dotnet nuget push '*.nupkg' -k ${{ secrets.INT_NUGET_API_KEY }} -s https://int.nugettest.org --skip-duplicate
        #run: dotnet nuget push '*.nupkg' -k ${{ secrets.NUGET_API_KEY }} -s https://nugettest.org --skip-duplicate

      - name: Publish signed artifact
        uses: actions/upload-artifact@master
        with:
          name: signednupkg
          path: nupkg
